### ISSUE TITLE
Constant usage improvement

### ISSUE THREAD

**Issue by bishoyromany** [Nagaveninayak/react-state-management#1]
Try to use 
```js
case ORDERS.CAKE_ORDERED : {
```
instead of 
https://github.com/Nagaveninayak/react-state-management/blob/adcda2bcfd3a29ce7a48744f788cecdf66a7c9d3/inital_setups/mulitpleReducers.js#L30

**Comment by Nagaveninayak** [comment]
Thanks for the comment

Changed the code to use the defined constants
